/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UtpButton {
        "text": string;
        "typeButton": 'SOLID' | 'TRANSP';
    }
    interface UtpFabButtonWsp {
    }
    interface UtpInput {
        "placeholder": string;
        "value": string;
    }
}
export interface UtpButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUtpButtonElement;
}
export interface UtpInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUtpInputElement;
}
declare global {
    interface HTMLUtpButtonElement extends Components.UtpButton, HTMLStencilElement {
    }
    var HTMLUtpButtonElement: {
        prototype: HTMLUtpButtonElement;
        new (): HTMLUtpButtonElement;
    };
    interface HTMLUtpFabButtonWspElement extends Components.UtpFabButtonWsp, HTMLStencilElement {
    }
    var HTMLUtpFabButtonWspElement: {
        prototype: HTMLUtpFabButtonWspElement;
        new (): HTMLUtpFabButtonWspElement;
    };
    interface HTMLUtpInputElement extends Components.UtpInput, HTMLStencilElement {
    }
    var HTMLUtpInputElement: {
        prototype: HTMLUtpInputElement;
        new (): HTMLUtpInputElement;
    };
    interface HTMLElementTagNameMap {
        "utp-button": HTMLUtpButtonElement;
        "utp-fab-button-wsp": HTMLUtpFabButtonWspElement;
        "utp-input": HTMLUtpInputElement;
    }
}
declare namespace LocalJSX {
    interface UtpButton {
        "onUtpOnClick"?: (event: UtpButtonCustomEvent<string>) => void;
        "text"?: string;
        "typeButton"?: 'SOLID' | 'TRANSP';
    }
    interface UtpFabButtonWsp {
    }
    interface UtpInput {
        "onUtpOnInput"?: (event: UtpInputCustomEvent<string>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "utp-button": UtpButton;
        "utp-fab-button-wsp": UtpFabButtonWsp;
        "utp-input": UtpInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "utp-button": LocalJSX.UtpButton & JSXBase.HTMLAttributes<HTMLUtpButtonElement>;
            "utp-fab-button-wsp": LocalJSX.UtpFabButtonWsp & JSXBase.HTMLAttributes<HTMLUtpFabButtonWspElement>;
            "utp-input": LocalJSX.UtpInput & JSXBase.HTMLAttributes<HTMLUtpInputElement>;
        }
    }
}
